openapi: 3.0.0
info:
  title: Insurance Management API
  version: 1.0.0
  description: API for managing insurance plans, activation, and reimbursement calculations.

paths:
  /coverage-plans:
    get:
      summary: Get available insurance coverage plans
      responses:
        '200':
          description: Coverage plans retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoveragePlan'

  /coverage/{userId}:
    post:
      summary: Activate insurance coverage for a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateCoverageRequest'
      responses:
        '200':
          description: Coverage activated

components:
  schemas:
    CoveragePlan:
      type: object
      properties:
        planId:
          type: string
        dailyCost:
          type: number
        maxCoverage:
          type: number
    ActivateCoverageRequest:
      type: object
      properties:
        planId:
          type: string
        paymentId:
          type: string
